postprocessor:
  name: crl
  APS_mode: False
  postprocessor_args:
    alpha: 5.0
    beta: 7.0
  postprocessor_sweep:
    alpha_list: [1.0, 2.0, 3.0, 4.0, 5.0]
    beta_list: [1.0, 2.0, 3.0, 4.0, 5.0]
